version: 2
jobs:
  build:
    docker:
      - image: poluhovichandrey/dotnet_core_centos

    steps:
      - checkout

      - run:
          name: rebuild

      - run:
          name: Build 
          command: dotnet build
