version: 2
jobs:
  build:
    docker:
      - image: poluhovichandrey/dotnet_core_centos

    steps:
      - checkout

      - run:
          name: Restore BillScanController
          command: dotnet "restore" "./BillScanController/BillScanController.csproj"

      - run:
          name: Build BillScanController
          command: dotnet "build" "./BillScanController/BillScanController.csproj"
